### ISSUE TITLE
G-lining an incorrectly formatted CIDR block g-lines everybody

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd#1201] opened 2016-08-20 00:39 UTC
So, I managed to gline the entire network by accidentally specifying an incorrectly formatted CIDR block. I meant to gline `*@2001:DB8:AAAA:BB00::/56`, instead I typed `*@2001:DB8:AAAA:BB00:/56` (note one less `:` in the mask) and this caused all users (including me but I have an E-line), including IPv4 users to get glined. The insane ban option is set to trigger at 25%, but obviously this setting didn't protect against this mistake. Full insane tag for reference: `<insane hostmasks="no" ipmasks="no" nickmasks="no" trigger="25">`

Now, I feel like this probably shouldn't have caused everyone to get glined in the first place, so this must be some parsing issue or something.

**Comment by attilamolnar** [comment] 2016-08-20 17:31
Duplicate of #977.

**Closed** 2016-08-20 17:31 UTC
Labels: duplicate
