### ISSUE TITLE
Error when compiling m_ssl_openssl on a fresh install of 2.0.26

### ISSUE THREAD

**Issue by sharstine** [inspircd/inspircd#1498] opened 2018-06-09 06:10 UTC
**Description**
Error when I run "make" on a new install of inspircd-2.0.26 with OpenSSL support.

**Steps to reproduce the issue:**
1. /configure
   * Would you like to enable SSL support? [y]
   * Would you like to enable SSL with m_ssl_openssl? [y]
   * Would you like to generate SSL certificates now? [y]
   * Go with defaults for everything else
2. make

**Describe the results you received:**
        BUILD:              modules/m_sqlauth.cpp
        BUILD:              modules/m_sqloper.cpp
        BUILD:              modules/m_ssl_openssl.cpp
/home/xxxxx/inspircd-2.0.26/src/modules/m_ssl_openssl.cpp: In static member function 'static void ModuleSSLOpenSSL::SetContextOptions(SSL_CTX*, long int, const std::string&, ConfigTag*)':
An error occured when executing: g++ -o modules/m_ssl_openssl.so -pipe -fPIC -DPIC -Woverloaded-virtual -Wshadow -Wformat=2 -Wmissing-format-attribute -Wall -O2 -g1 -Iinclude -DMODNAME=m_ssl_openssl.so -fPIC -shared -rdynamic /home/xxxxx/inspircd-2.0.26/src/modules/m_ssl_openssl.cpp -lssl -lcrypto
/home/xxxxx/inspircd-2.0.26/src/modules/m_ssl_openssl.cpp:152: error: 'SSL_CTX_clear_options' was not declared in this scope
*** Error code 1

Stop in /home/xxxxx/inspircd-2.0.26/build.
*** Error code 1

Stop in /home/xxxxx/inspircd-2.0.26.
xxxxx@yyyyy:/home/xxxxx/inspircd-2.0.26>

**Describe the results you expected:**
InspIRCd should compile without error.

**Additional information you deem important:**
OS is FreeBSD 7.3-RELEASE-p7.

Output of g++ --version and gcc --version is:
g++ (GCC) 4.2.1 20070719 [FreeBSD]

clang isn't installed on the server I'm using, so that's not an option for me.

**Output of `./bin/inspircd --version`:**
Output of ./inspircd version is:
InspIRCd version: InspIRCd-2.0.26(r0)

**Comment by sharstine** [comment] 2018-06-09 17:57
OpenSSL 0.9.8e 23 Feb 2007

**Comment by SaberUK** [comment] 2018-06-10 10:47
Your version of OpenSSL is too old. You need to update to a newer version (at least 0.9.8n but ideally 1.1).

**Comment by sharstine** [comment] 2018-06-11 00:49
I contacted my hosting provider and discovered there's a newer version of OpenSSL at a different path:

xxxx@yyyy:/home/xxxx/inspircd-2.0.26> /usr/local/openssl/bin/openssl version
OpenSSL 1.0.2n  7 Dec 2017

Is there a way to have InspIRCd detect OpenSSL at this path?

**Comment by SaberUK** [comment] 2018-06-14 15:56
You should add its pkg-config directory (i'd guess this would be something like /usr/local/openssl/lib/pkgconfig) to your PKG_CONFIG_PATH in the environment and then run `./configure --clean`.

As this is not a bug i'll be closing it now. Please ask in #inspircd on irc.chatspike.net if you have any more issues.

**Closed by SaberUK** 2018-06-14 15:56 UTC
