### ISSUE TITLE
m_dnsbl is failing to act on clients that are matched on DNSBLs while Anope and HOPM are, all using the same configured blacklists

### ISSUE THREAD

**Issue by Techman** [inspircd/inspircd#1436] opened 2017-12-06 17:51 UTC
With the advent of "Little Marco" and his proxy lists, I've noticed that InspIRCd 2 is, on occasion, failing to ban hosts (the action is configured as ZLINE like most networks would do), leaving a secondary solution such as Anope or HOPM having to ban these clients themselves.

I have no idea what is causing this, but I thought originally that the DNS lookups may be timing out, but after adding `<dns>` blocks with Google DNS' IPs and a timeout of 10s, the issue did not stop.

**Comment by Cronus89** [comment] 2017-12-06 18:00
I have definately had this and a few others have too.  I mentioned it a few times over the last year or two on #inspircd 

Without a secondary DNSBL System in place, m_dnsbl is half useless.

**Comment by SaberUK** [comment] 2017-12-06 19:50
It would be useful to know what DNSBLs you are using and what the IP addresses which were evading m_dnsbl are.

**Comment by xnite** [comment] 2017-12-06 21:19
@SaberUK I can only speak for myself on which ones I use (efnetrbl, dronebl, dnsbl.im, tor.dan.me.uk) I often times find that inspircd doesn't catch them the first time around, but the second time around with HOPM they are caught.
We use the same blacklists on a private network with about 3-5k users online at any given time, and constant connect/disconnects. Our custom bot there catches hundreds of entries that should have been caught by the IRCd in the first place.

**Comment by IotaSpencer** [comment] 2017-12-06 21:24
Same, I have checked IPs against my blacklists and sometimes the m_dnsbl will work and deny them, sometimes it lets them through. So 90% of the IPs getting through are on the list, but m_dnsbl won't catch that.

**Comment by SaberUK** [comment] 2017-12-10 13:21
It would be useful to have your exact DNSBL config for both InspIRCd and HOPM/Anope too. I can't really debug anything without knowing that.

**Comment by IotaSpencer** [comment] 2017-12-24 04:18
## Hopm
```
blacklist {
        name = "rbl.dnsbl.im";
        type = "A record reply";
        reply {
                1 = "Tor";
                2 = "HTTP(S)";
                3 = "Socks4/5";
                4 = "Open Router";
                5 = "Abusive host";
                #7 = "Compromised MTA/Mail Servers";
        };
        ban_unknown = no;
        kline = "PRIVMSG OperServ :AKILL ADD *@%i !T 7d Your IP address has been blacklisted! For more information visit https://www.dnsbl.im/lookup?ip=%i";
};
```

## InspIRCD

```
#    1 = "Tor";
#    2 = "HTTP(S)";
#    3 = "Socks4/5";
#    4 = "Open Router";
#    5 = "Abusive host";
#    7 = "Compromised MTA/Mail Servers"
<dnsbl
    name="DNSBLim"
    type="record"
    domain="rbl.dnsbl.im"
    action="ZLINE"
    reason="Your IP address has been blacklisted! For more information visit https://www.dnsbl.im/lookup?ip=%ip%"
    duration="7d"
    records="1,2,3,4,5,7"
>
```

**Comment by SaberUK** [comment] 2017-12-24 10:32
Thanks, i'll look into this.

**Comment by xnite** [comment] 2017-12-24 17:13
Another one for you @SaberUK 
## ircd
```XML
<dnsbl
  name="dronebl"
  type="record"
  domain="dnsbl.dronebl.org"
  action="ZLINE"
  reason="You have a host listed in the DroneBL. For more information, visit http://dronebl.org/lookup_branded?ip=%ip%"
  duration="3d"
  records="3,5,6,7,8,9,10,13,14,15,17,255"
>
```
## hopm
```
blacklist {
  name = "dnsbl.dronebl.org";
  address_family = ipv4;
  type = "A record reply";
  ban_unknown = no;
  reply {
    3 = "IRC spam drone (litmus/sdbot/fyle)";
    5 = "Bottler (experimental)";
    6 = "Unknown worm or spambot";
    7 = "DDoS drone";
    8 = "Open SOCKS proxy";
    9 = "Open HTTP proxy";
    10 = "ProxyChain";
    13 = "Automated dictionary attacks";
    14 = "Open WINGATE proxy";
    15 = "Compromised router / gateway";
    17 = "Automatically determined botnet IPs (experimental)";
    255 = "Uncategorized threat class";
  };
  kline = "OS AKILL ADD *@%i !T 3d You have a host listed in the DroneBL. For more information, visit http://dronebl.org/lookup_branded?ip=%i&network=BuddyIM";
};
```

**Comment by Techman-** [comment] 2017-12-29 09:32
I have submitted my DNSBL config to @SaberUK in private message since I don't publicly list all of the DNSBLs I use except to affected users. You folks are welcome to Saber or me for the list but I won't post it publicly here.

As per @Robby- , I'm going to mention #975 here because I also noted in #inspircd.dev that sometimes the DNS resolver is not resolving user hostnames when connecting, which causes issues with G-Lines, connect blocks, etc.

**Comment by SaberUK** [comment] 2018-03-22 14:19
I can't reproduce this on the latest 2.0 git the example given by @xnite.

I'm wondering about whether intermittent DNS resolution issues could be the cause...

**Comment by satmd** [comment] 2018-04-03 18:36
I'm bit late to the show, sorry for that.

The first post is about 80.79.23.112, the result of *today* is 127.0.0.9. The tests are for codes 1, 3, 4, 5 and 7. As such m_dnsbl would not catch that IP today.

If this problem still is happening, please post another example. Please include the output of "dig d.b.c.a.dnsbl.dronebl.org" from the same machine (where d.b.c.a is the *reversed* IP address) and the relevant parts of the hopm and m_dnsbl config parts.

The issue #975 suggests that there might be an underlying problem with dns which sounds more likely to be the cause for this issue. m_dnsbl actually has little code that could go wrong just *sometimes*. I will follow up the other bug, too.

**Comment by SadieCat** [comment] 2021-12-29 10:25
Can DNSBLs return multiple A records for a single host? I just had a thought that as the DNSBL module only checks the first record returned if the DNSBL returns multiple records and the first A record isn't a match then it would probably fail to match the latter records too.

(cc: @duckspike)

**Comment by SadieCat** [comment] 2022-04-18 12:30
This should be fixed with the DNS changes in recent 3.x releases. Please reopen if this is not the case.

**Closed by SadieCat** 2022-04-18 12:30 UTC
Labels: bug, need more information
