### ISSUE TITLE
Use GetFullRealHost() instead of GetFullHost() when user has users/auspex priv

### ISSUE THREAD

**Issue by iwalkalone69** [inspircd/inspircd#1611] opened 2019-04-23 10:49 UTC
**Description**

It is useful for operator and some kind of robots to receive in all messages the real IP instead of displayed host. It is working for WHO/WHOIS currently but it would be useful for the rest of protocol (PRIVMSG/NOTICE/etc).

**Steps to reproduce the issue:**
1. Connect a user with users/auspex priv (aka Bot).
2. Connect any other user (it will receive a displayed host to hide its IP).
3. Send a message from the regular user (2) to the robot (1). It will not see the real IP in the PRIVMSG line.

**Describe the results you received:**

We receive the displayed host.

**Describe the results you expected:**

I would like to receive the real IP if the user has users/auspex priv.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**

InspIRCd-3.0.0-49fef4ef7

**Comment by SaberUK** [comment] 2019-04-23 11:34
WHO has a specific flag to enable viewing the real host and WHOIS has it in a separate field. I'm not really sure how we could expose it like this in other messages.

**Comment by Robby-** [comment] 2019-04-23 11:38
Seems related to #1408.

**Comment by SaberUK** [comment] 2019-04-23 11:43
Yes, this is a duplicate of #1408.

**Closed by SaberUK** 2019-04-23 11:43 UTC
Labels: enhancement, minor
