### ISSUE TITLE
ZNC/psyBNC need to /hop on connect to see channel OP (+o) 

### ISSUE THREAD

**Issue by caiot5** [inspircd/inspircd#1949] opened 2021-12-05 02:12 UTC
**Description**

When connecting through an IRC Bouncer like ZNC and psyBNC (both tested), when the user logs out the BNC and log on again, the user can't see channel operators (+o users) and therefore they need to /hop so they can see it.
If the user is a channel operator he can still kick / ban / etc but without any @ icon on his nickname.
This behavior is confirmed through multiple IRC clients, so it's no client-side problem and it only occurs with inspircd-based networks, there is no problem at all with other IRCds

**Steps to reproduce the issue:**

1. Connect ZNC on an Inspircd-based Network
2. Disconnect from your ZNC account (leaving the znc connected to the network)
3. Connect to your ZNC again
4. You will not be able to see the +o users on the channels you joined before leaving ZNC

**Describe the results you received:**

I am not able to see the operators on the channel

**Describe the results you expected:**

I wish I could see the channel operators on channel =)

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every single time and affects both ZNC and psyBNC

**Output of `./bin/inspircd --version`:**

InspIRCd-3.11.0

**Comment by genius3000** [comment] 2021-12-05 02:33
This is indeed a client/bouncer issue, see #1709 which this is a duplicate of and the reply there for further information.

**Closed by genius3000** 2021-12-05 02:33 UTC

**Comment by SadieCat** [comment] 2021-12-05 07:36
You can fix this by updating to ZNC 1.8.
