### ISSUE TITLE
/WHO 0 o returns all opers even hidden ones

### ISSUE THREAD

**Issue by KoraggKnightWolf** [inspircd/inspircd#1651] opened 2019-05-24 18:26 UTC
**Description**

**Steps to reproduce the issue:**

1. Have a user /OPER up and set themselves +H (hideoper)
2. (If on 2.0.x install the extra m_whox.cpp module)
3. Have a non oper user run /who 0 o and observe how they will see all opers, even those set +H

**Describe the results you received:**

The non oper user sees ALL opers even hidden ones (by usermode +H)
**Describe the results you expected:**

The non oper user would not see opers who have user mode +H set upon them
**Additional information you deem important (e.g. issue happens only occasionally):**

This issue occurs on InspIRCd 3 and on the "old" 2.0.x series (the latter with the m_whox.cpp module).
**Output of `./bin/inspircd --version`:**
old stable (2.x): InspIRCd-2.0.27 r0
new stable (3.x) InspIRCd version: 3.1.0-96cc17f65

**Comment by KoraggKnightWolf** [comment] 2019-05-24 18:31
It is possible that as the mentioned network and mine are linked via PyLink and it is not fully adapted to InspIRCd 3 yet that this might be causing the strange behaviour. The bug definetely exists in the v2 extras module though so could also exist in v3 still.

Regards,

Koragg

**Comment by SaberUK** [comment] 2019-05-27 09:24
I think that this is a PyLink issue as I can't replicate this on v3. Can you verify whether the visible opers it shows are on a v3 server which is linked solely through v3 servers?

(I'm not planning on fixing any bugs in the v2 extras module as it was only backported so that client developers could test their WHOX implementation before v3 was released).

**Comment by KoraggKnightWolf** [comment] 2019-05-31 23:44
This might indeed be a PyLink issue has it does not have an update for dealing with InspIRCd 3 perfectly just yet. I will leave this open just incase it MIGHT be an issue on Insp end after all, just to be safe.

**Comment by jlu5** [comment] 2019-06-01 00:37
I can't reproduce when this linking PyLink to an Insp3 server. Are the affected users solely PyLink clients, or something else?

**Comment by SaberUK** [comment] 2019-07-22 12:11
As there hasn't been any responses to this in over a month i'm going to close it. Please reopen if you can replicate it on an InspIRCd-only network.

**Closed by SaberUK** 2019-07-22 12:11 UTC
Labels: need more information
