### ISSUE TITLE
Quit: Result too large

### ISSUE THREAD

**Issue by gnettorg** [inspircd/inspircd#583] opened 2013-07-06 20:38 UTC
Users get disconnected with quit message "Result too large" on servers running on windows machines

**Comment by attilamolnar** [comment] 2015-05-15 13:26
Is this (people quitting by themselves on a Windows inspircd) still an issue?

We have failed to reproduce it so far using lightirc. As far as I know the error message "An existing connection was forcibly closed by the remote host." is the Windows equivalent of "Connection reset by peer" (Windows generates a different message). It is something that occurs all the time on a network for a dozen of reasons including network issues or more esoteric problems like security software malfunction on the client side as pointed out by @md-5 so this error message does not help much in identifying the issue.

Are you (@gnettorg @mickeyunagee @WindowsUser) sure this is an inspircd issue? If you can reproduce this at will please post the steps so we can take a look.
How long the client has to be connected for this to occur? What Windows version? How often does the disconnection happen?

**Comment by MandL27** [comment] 2015-05-15 13:31
@attilamolnar It seems to happen somewhat at random for me (on various networks with different ircds; the only common thread is that I use Windows' HexChat), but it usually impacts anything Internet-related (whether it's just on my computer or on the router is unknown) since Chrome lags as well.

**Comment by attilamolnar** [comment] 2015-05-15 13:35
@MandL27 If it occurs on various ircds and even with other internet related programs then I don't see how is that related to this issue. It might be caused by NAT timeout.

**Comment by WindowsUser** [comment] 2015-05-26 21:59
@attilamolnar yes this was done over a NAT. I don't have this setup anymore though and never see this issue.

**Comment by attilamolnar** [comment] 2015-05-27 20:21
Please reopen if the issue still exists.

**Closed by attilamolnar** 2015-05-27 20:21 UTC
Labels: bug, needinfo, windows
