### ISSUE TITLE
[2.0] CGIIRC: Lines don't work if real IP is E-Lined

### ISSUE THREAD

**Issue by B00mX0r** [inspircd/inspircd#989] opened 2015-02-07 22:38 UTC
When G-lining and Z-lining a host connected via WEBIRC, it won't do anything if the router's IP is E-lined. Example: 1.1.1.1 sends a WEBIRC for user "User1", telling the server that this user's IP and host mask are 1.1.1.2. If 1.1.1.1 is E-lined, then lines placed on 1.1.1.2 won't work. So if I Z-line 1.1.1.2, it won't actually work. It works fine if 1.1.1.1 isn't E-lined. This behavior also applies to DNSBL, where DNSBL won't check 1.1.1.2 to see if it's blacklisted.

Version: Latest insp20 code (2.0.19 I guess). Untested on other versions (it may also apply to 2.2).

**Comment by B00mX0r** [comment] 2015-02-08 08:24
If I'm right, then the code sets an exempt flag on a connection if it detects an e-line. Since the user originally connects via the real IP, I think that it's setting the exempt flag but then doesn't unset it on webirc or cgiirc.

**Comment by JDowny** [comment] 2015-02-08 08:46
I can't replicate this...

<code>* *** ANNOUNCEMENT: Connecting user 490AAAADG detected as using CGI:IRC (127.0.0.1), changing real host to 192.168.0.100 from 127.0.0.1
* *** CONNECT: Client connecting on port 6697 (class mainsubs): asdfafsdasdfasfd!webirc@192.168.0.100 (192.168.0.100) [http://testnet.com]
* *** XLINE: TinMan added permanent E-line for *@127.0.0.1: test
* *** XLINE: TinMan added timed Z-line for 192.168.0.100, expires on Sun Feb  8 01:36:35 2015: test
* *** QUIT: Client exiting: asdfafsdasdfasfd!webirc@192.168.0.100 (192.168.0.100) [Z-Lined: test]</code>

Or am I misunderstanding this?

**Comment by B00mX0r** [comment] 2015-02-08 08:51
You're unable to replicate this because you add the E-line after the client is connected. The E-line must be added before, because this is what happens:

1) Client connects with 127.0.0.1
2) user->exempt status is set since 127.0.0.1 is E-lined
3) WEBIRC, ok, IP for client now 192.168.0.100
4) We check for lines on 192.168.0.100, but return false since the user's exempt flag is set to true

**Comment by JDowny** [comment] 2015-02-08 08:55
`* *@127.0.0.1 1423384571 0 TinMan :test
* *@192.168.0.117 1423384289 0 TinMan :test
* e :End of /STATS report
* *** ANNOUNCEMENT: Connecting user 490AAAADJ detected as using CGI:IRC (127.0.0.1), changing real host to 192.168.0.100 from 127.0.0.1
* *** CONNECT: Client connecting on port 6697 (class mainsubs): asdfafsdasdfasfd!webirc@192.168.0.100 (192.168.0.100) [http://testnet.com]
* *** XLINE: TinMan added timed Z-line for 192.168.0.100, expires on Sun Feb  8 01:53:04 2015: test
* *** QUIT: Client exiting: asdfafsdasdfasfd!webirc@192.168.0.100 (192.168.0.100) [Z-Lined: test]`

The eline was there before I connected this second time, as indicated in the stats output. Am I still missing something?

**Comment by B00mX0r** [comment] 2015-02-08 08:57
Are you using InspIRCd v2.2? I haven't tested to see if the issue exists on it, but I've been able to replicate this on a clean environment (and fix it using the pull request I just made).

**Comment by JDowny** [comment] 2015-02-08 08:58
No this is 2.0.18, the latest release in the 2.0 branch. 

It is not pulled from git, but I don't think there has been any changes in the 2.0 branch for CGI:IRC on git that I wouldn't have.

**Comment by B00mX0r** [comment] 2015-02-08 08:58
Can I see your CGI:IRC block?

**Comment by JDowny** [comment] 2015-02-08 09:00
Sure, here is all my relevant CGI:IRC config:

`<module name="m_cgiirc.so">`
`<cgiirc opernotice="yes">`
`<cgihost type="webirc" password="fish" mask="127.0.0.1">`

**Comment by B00mX0r** [comment] 2015-02-08 09:01
Looks fine to me. It may have something to do with DNSBL being loaded, since that messes with CGIIRC and E-lines a bit (see https://github.com/inspircd/inspircd/commit/fe9e5947552cc8b044a7ce47ffbee06ee7283886).

**Comment by JDowny** [comment] 2015-02-08 09:03
I do have m_dnsbl loaded as well, I remember this whole issue with CGI:IRC and elines/dnsbl years ago but since the fix you linked I have had no issues (not implying maybe some don't exist, as you seem to show).

`<module name="m_dnsbl.so">1`
`<dnsbl name="DroneBL" type="bitmask" domain="dnsbl.dronebl.org" action="ZLINE" reason="DroneBL" duration="30d" bitmask="253">`

**Comment by B00mX0r** [comment] 2015-02-08 09:09
This is certainly an odd problem. The logs report a negative hit when this occurs, and it really treats the user as though they're Z-lined. I can, however, confirm that my pull request did fix it in my environment. I'll try to track it down more tomorrow.

**Comment by SaberUK** [comment] 2015-02-08 12:11
Possibly related: https://github.com/inspircd/inspircd/commit/c8b344ea748d62d9f37cacd4dd785f15b186725c

**Comment by attilamolnar** [comment] 2015-02-12 15:40
@B00MX0R Please supply a /MODULES list on an affected server

**Comment by B00mX0r** [comment] 2015-02-12 18:35
http://pastebin.com/PjYKSvB1

**Comment by attilamolnar** [comment] 2015-02-12 19:42
`[02/12/2015 10:34:15 AM] 0xe4efa0 m_xline_sql.so -v-- :Keeps a dynamic log of all XLines created, and stores them in a MySQL database. - InspIRCd-2.0.18 rv2.0.18-36-gf8185fe`

This module is not distributed with inspircd and it's not in inspircd-extras either can you point me to the code?

**Comment by B00mX0r** [comment] 2015-02-12 19:49
http://pastebin.com/hNXcmHM5

**Comment by attilamolnar** [comment] 2015-04-17 01:30
Fixed by reverting the commit causing the regression. I've not added this to a milestone because it didn't affect the released version (2.0.18), but I'll mention your name in the news post because this would not have been discovered without your testing efforts.

**Closed by attilamolnar** 2015-04-17 01:30 UTC
