### ISSUE TITLE
m_pbkdf2 only has one hash provider (and none on reload)

### ISSUE THREAD

**Issue by Elizafox** [inspircd/inspircd#1818] opened 2020-11-27 23:53 UTC
**Description**

m_pbkdf2 only loads with one hash provider enabled despite having other hash providers loaded (on my server, sha256). Other hashes like pbkdf2-hmac-sha1 don't work. Reloading the module does worse than nothing: after reload, no providers seem to exist anymore.

This issue persists no matter what order pbkdf2 comes in the config file.

This issue occurs on at least InspIRCd 3.8.1.

**Steps to reproduce the issue:**

1. Specify md5, sha1, sha256 then pbkdf2 in the config file. Order doesn't seem to matter.
2. Start the ircd
3. Attempt to run `/mkpasswd pbkdf2-hmac-sha1 blah`, `pbkdf2-hmac-sha256`, `pbkdf2-hmac-md5`
4. Reload the module with `/RELOADMODULE`

**Describe the results you received:**

Only pbkdf2-hmac-sha256 works, the rest only return "Unknown hash type."

Reloading the module causes **None** of the hash providers to work.

**Describe the results you expected:**

For at least -sha1 and -md5 to work as well.

For all providers to work on module reload.

**Additional information you deem important (e.g. issue happens only occasionally):**

Order in the config file is irrelevant, tested loading pbkdf2 before sha1, sha256, md5, after, and even in the middle of each.

md5 and sha1 still work as expected.

**Output of `./bin/inspircd --version`:**

`InspIRCd version: 3.8.1`

**Comment by genius3000** [comment] 2020-11-28 01:56
Looks like the issue with m_sha1 specifically is that its defined name still has a `hash/` prefix, then HashProvider prepends another `hash/`.  
I tried another test, reloading the hash provider modules after start/reload of pbkdf2, they all work then. I haven't dug in further but seems like the OnServiceAdd hook isn't working for initial load.

**Comment by ShutterQuick** [comment] 2020-11-30 17:17
I had a look at what happens here.
It looks like we have a regression in how modules are notified of services compared to insp20.
Now `OnServiceAdd` is only called when as a service becomes available, and it doesn't receive what modules are already available as it is loaded.

This means that the order the modules are loaded in matters.
E.g. in my testing:
```
MODULE: Initializing m_md5.so
MODULE: Initializing m_pbkdf2.so
MODULE: Initializing m_sha256.so
```

`pbkdf2-hmac-sha256` works, as `sha256` loaded after `m_pbkdf2`, while `pbkdf2-hmac-md5` does not, as `m_md5` was loaded before. If I `unloadmodule m_md5` and then load it again, it is registered correctly.

**Comment by SadieCat** [comment] 2020-12-09 23:36
This should be fixed in insp3 git.

**Closed by SadieCat** 2020-12-09 23:36 UTC
Labels: bug
