### ISSUE TITLE
[SUGGESTION]: Add 'shun' option in /filter actions

### ISSUE THREAD

**Issue by westor7** [inspircd/inspircd#483] opened 2013-04-10 12:46 UTC
Hello,

I wanna suggest to add the SHUN option tin actions of filter so if filter triggers with shun action then an shun will be add to the users host.

e.g: /quote filter _testt_ shun \* :testt filter

[15:43:25] -> Server: filter _testt_ shun \* :testt filter
[15:43:29] -darkness2.chatnet.gr- **\* Invalid filter type 'shun'. Supported types are 'gline', 'none', 'block', 'silent' and 'kill'.
- Thanks!

**Comment by cehib** [comment] 2016-03-22 14:31
@attilamolnar hi you closed my issue 1158 but i come here and there is no solution pls help ?

**Comment by Heufneutje** [comment] 2016-03-22 15:25
It was closed because it was a duplicate of this issue. There's no need to track the same issue multiple times. It's marked to be implemented in InspIRCd 2.2.

**Comment by cehib** [comment] 2016-03-23 14:24
nearly 3 years open and not fixed, thats why i open new ticket

ty anyway will go back to unreal for now

**Comment by SaberUK** [comment] 2016-03-23 20:52
Opening new tickets will not make it get added faster. We only have a limited amount of resources and can't add every feature at once.

**Closed** 2017-12-22 01:08 UTC
Labels: enhancement, minor
