### ISSUE TITLE
"hidekills" does not properly mask the identity of the oper

### ISSUE THREAD

**Issue by sebastianbarfurth** [inspircd/inspircd#1015] opened 2015-03-17 22:23 UTC
A kill performed with hidekills active will still pass the performing opers name and host to the user who has been killed.

Here is the output as parsed by IRCCloud:

```
23:19:29 :Snoonet Network Operations KILL aFreshMelonKilled :cosmos.snoonet.org!snoonet/operations-manager/aFreshMelon!Snoonet Network Operations (Killed (Snoonet Network Operations ()))
23:19:29 Closing link: (sid25548@id-25548.brockwell.irccloud.com) [Killed (Snoonet Network Operations ())]
```

You can see that it reveals the opers name and host (in this case myself).

**Comment by SaberUK** [comment] 2015-03-17 22:33
[Confirmed](https://github.com/inspircd/inspircd/blob/insp20/src/commands/cmd_kill.cpp#L137), but you shouldn't be using spaces in your `hidekills` value or you will break clients

**Comment by aFreshMelon** [comment] 2015-03-17 22:35
Thanks @SaberUK

**Comment by Adam-** [comment] 2015-03-17 22:37
The host is passed as part of the kill path, but the nick is hidden. You only see your nick there because it is in your host.

**Comment by aFreshMelon** [comment] 2015-03-17 22:39
Right. But why is the opers host passed at all? I don't think it's uncommon for staff to have their name contained in their host.

**Comment by SaberUK** [comment] 2015-03-20 13:11
Probably because some other implementation (Unreal?) did it that way and we copied them.

**Comment by aFreshMelon** [comment] 2015-03-20 13:40
I'd still love it if it was changed or if there was an option to change it.

**Comment by Adam-** [comment] 2015-03-20 14:06
I wouldn't mind just removing the kill path from the server to client KILL message. Many modern IRCds do not send it (hybrid, ratbox, charybdis).

**Comment by SaberUK** [comment] 2015-03-20 14:14
@aFreshMelon Could you test this? https://github.com/SaberUK/inspircd/commit/8a7fdfc4242c

**Comment by aFreshMelon** [comment] 2015-03-20 14:35
It works, though it does have some weird parenthesis.

```
15:34:01 ⇐ You were killed
15:34:01 Closing link: (sid25548@brockwell.irccloud.com) [Killed (irc.snoonet.org ())]
```

**Comment by attilamolnar** [comment] 2015-10-11 14:45
Fixed by @SaberUK in #1018.

**Closed by attilamolnar** 2015-10-11 14:45 UTC
