### ISSUE TITLE
Insufficient parameters for command 'FMODE' on ban-removal

### ISSUE THREAD

**Issue by shaggie76** [inspircd/inspircd#1462] opened 2018-02-20 20:51 UTC
We run a moderately large IRC server cluster to handle ~100K users at once and have been using InspIRCd for years. We recently moved from single-instance servers with 4 spokes linked to a hub to balance the load across multiple processors and this has allowed us exceed 130K users at once.

With a community that large we have to /TBAN a lot of people to give them time to reflect on peace and goodwill in silence. Unfortunately, since we switched to a cluster of linked servers we've encountered a problem: sometimes channel ban entries refuse to be removed. People regularly complain about their unfair punishment and what we've found is that sometimes they have lingered in the ban table much longer than intended.

Although I've never seen it in the act when I mode -b of these lingering bans by hand I get this:

[11:36:41] -irc5.warframe.com- *** REMOTELINK: From irc0.warframe.com: Connection to 'irc3.warframe.com' failed with error: Insufficient parameters for command 'FMODE'
-
[11:36:44] -irc5.warframe.com- *** REMOTELINK: Server irc3.warframe.com split from server irc0.warframe.com with reason: Insufficient parameters for command 'FMODE'
-
[11:36:44] -irc5.warframe.com- *** REMOTELINK: Netsplit complete, lost 4197 users on 1 server.

Of course, this never happens promptly -- once cluster here has been up for 11 days and has no ghosts yet. I think it's only a matter of time, though

Upon consulting #inspircd I upgraded from v2.0.24 to 2.0.25 but we've seen it since the upgrade again.

I've tried extensively on a test cluster to reproduce the issue with no luck.

InspIRCd-2.0.25 r0

Full disclosure: this might be entirely our fault, we have a custom module that replicates bans to related channels on our server: https://pastebin.com/Q3YWVapG

This works flawlessly for weeks at a time so if it's to blame I'd be surprised (but grateful to know why)

**Comment by genius3000** [comment] 2018-02-20 23:04
Do you currently have any logging of `m_spanningtree`? If not could you add to your servers (adjust target as needed):
```
<log method="file" type="m_spanningtree" level="sparse" target="logs/spanningtree.log">
```
Then rehash.

As seen [here](https://github.com/inspircd/inspircd/blob/insp20/src/modules/m_spanningtree/treesocket2.cpp#L480...L487), the whole mode string is logged at level SPARSE when you recieve that error. It may help narrow this down a bit.

**Comment by shaggie76** [comment] 2018-02-21 02:45
Ok, will do -- I also rewrote our mod broadcasting to use a ModeWatcher instead as was a advised in chat. I'll deploy both changes tomorrow.

**Comment by shaggie76** [comment] 2018-02-21 03:01
It turns out this was already logging and I never spotted it in the logs before:
```
InspIRCd0/run/logs/ircd.log:Tue Feb 20 08:47:23 2018: Insufficient parameters for S2S command :144ABE01J FMODE #T_EN_EU 1517236106
InspIRCd0/run/logs/ircd.log:Tue Feb 20 08:47:54 2018: Insufficient parameters for S2S command :144ABE01J FMODE #T_EN_EU 1517236106
InspIRCd0/run/logs/ircd.log:Tue Feb 20 16:18:59 2018: Insufficient parameters for S2S command :918AAAAAJ FMODE #T_DE 1519134515
```
I'm not sure that this helps per se -- when the server gets in this state again I can correlate what I entered with what was logged.

**Comment by shaggie76** [comment] 2018-02-21 03:05
Huzzah: repro!
```
/mode #T_EN_EU b

[10:03:24] #T_EN_EU TiberianSon!*@* set by irc5.warframe.com (Tue Feb 20 17:06:51 2018)
[10:03:24] #T_EN_EU gatojordan7_7!*@* set by irc5.warframe.com (Tue Feb 20 15:55:34 2018)
[10:03:24] #T_EN_EU HeintaiDragon7O2!*@* set by irc5.warframe.com (Tue Feb 20 14:07:40 2018)
[10:03:24] #T_EN_EU PETIT38!*@* set by irc5.warframe.com (Tue Feb 20 13:38:30 2018)
[10:03:24] #T_EN_EU End of channel ban list

/mode #T_EN_EU -b PETIT38!*@*

[10:03:36] -irc5.warframe.com- *** LINK: Connection to 'irc0.warframe.com' failed with error: received ERROR Insufficient parameters for command 'FMODE'
[10:03:38] -irc5.warframe.com- *** LINK: Server irc0.warframe.com split: received ERROR Insufficient parameters for command 'FMODE'

and in server log
InspIRCd0/run/logs/ircd.log:Tue Feb 20 22:03:34 2018: Insufficient parameters for S2S command :144AABFKE FMODE #T_EN_EU 1519134511
````
I want to say this isn't my code running because it's barfing on T_EN_EU and my module would be broadcasting the mode to other channels.

**Comment by genius3000** [comment] 2018-02-21 08:58
I've been trying to reproduce this with a three server test net, tban, and your ban propagation code. So far, no luck.  
Your logs show that the mode parameters are missing somehow. It's only sending the channel name and age. Do you have any other functions or modules that catch any mode-related events, outside of the InspIRCd core stuff?

**Comment by SaberUK** [comment] 2018-02-21 10:35
Possibly related commit: 5f29158a5b7a892bde7dff26d87f94aacc8beadb

cc: @Adam-

**Comment by shaggie76** [comment] 2018-02-21 14:10
Hmm, that's the only OnMode handler we have -- the rest is a minimal set of modules.

I rewrote our OnMode handler to use a ModeWatcher last night -- I'll try deploying that this morning after I read my diffs with coffee-eyes.

**Comment by shaggie76** [comment] 2018-02-21 14:45
https://pastebin.com/D40UpRzt is the mode watcher -- pretty simple, seems to be working just fine

**Comment by genius3000** [comment] 2018-02-22 03:54
So, I was able to reproduce this finally. I haven't gotten any further than that, will get back at it later tonight. It's either with ban syncing during burst/channel creation or due to a possible desync with your ban propagation function. Either way, the core should maybe handle it before sending an invalid FMODE I'm thinking.

**Comment by shaggie76** [comment] 2018-02-24 22:34
Amazing! I'm super curious how you got it to happen -- I tried carefully for _hours_.

**Comment by SaberUK** [comment] 2018-03-22 13:43
This was found to be a bug in @shaggie76's custom code.

>Either way, the core should maybe handle it before sending an invalid FMODE I'm thinking.

I initially agreed with this but i've looked into it and it doesn't seem like something which would easily implementable in the 2.0 branch.

---

As this has been resolved i'm going to close the issue.

**Closed by SaberUK** 2018-03-22 13:43 UTC
