### ISSUE TITLE
Users connected via a /ELINEd webirc host do not have their actual IP checked for lines, shuns etc.

### ISSUE THREAD

**Issue by pxdnbluesoul** [inspircd/inspircd#1800] opened 2020-10-05 03:10 UTC
**Description**

If an E-Line is set on a webirc host (1-2-3-4.amazonaws.com), and a larger Z-Line is set on the network around it (*.amazonaws.com), a user using the webirc host via an address in scope of a line is also exempted from lines, shuns etc.

**Steps to reproduce the issue:**

1. Place a /zline on a user IP address
2. Place a /eline on a webirc host with a valid connect block
3. Connect to the IRCD via the excepted webirc host

**Describe the results you received:**

The connection is not only allowed, but the user is immune to /shun, /gline, etc.

**Describe the results you expected:**

The IP and host would be re-checked once the webirc handoff is complete.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is happening very consistently, we were able to resolve all issues of problem users walking through lines and talking through shuns by removing this single-host ELINE and the larger-network ZLINE, but this is likely a stopgap fix for us.

**Output of `./bin/inspircd --version`:**

3.7.0 tarball pulled from github and compiled on Amazon Linux 2.

**Comment by SadieCat** [comment] 2020-10-05 15:34
I can't seem to replicate this which is odd.

**Comment by pxdnbluesoul** [comment] 2020-10-05 22:05
I don't know what would be beneficial here, but to be more specific, I had a GLINE placed on *@*.amazonaws.com and later an ELINE placed at *@ec2-(ip-address-with-dashes).us-east-2.compute.amazonaws.com for a webirc client (The Lounge, latest stable). Once that was placed, we observed that sessions initiated from the ELINEd webirc server were fully exempt from all actions including G and Z lines, SHUNs, and even AKILLs placed by OperServ on Atheme latest stable.

**Comment by genius3000** [comment] 2020-10-06 02:35
I'd like to have a few things clarified here, for proper tracking:
1) Please paste the exact version given from `./bin/inspircd --version` as requested in the template.
2) Post a snippet of your m_cgiirc->cgihost tags, removing/redacting any sensitive information.

As a note, I couldn't reproduce this yet either. Tested with a webirc host (cgihost tag of webirc type) E-lined on both v4 and v6 IP addresses, Z-lining an IP address well outside any close range and the Z-line worked. I'll test with more debug logging when I get the chance.

**Comment by genius3000** [comment] 2020-10-06 02:42
@pxdnbluesoul

I have an idea for you to test. Remove the matching `*@host` E-line and instead add an E-line of `*@IP`. Then see if other X-lines will correctly affect users after successful WEBIRC handoff.

**Comment by SadieCat** [comment] 2020-10-06 09:50
@pxdnbluesoul Does the latest git fix this issue?

**Comment by pxdnbluesoul** [comment] 2020-10-06 14:09
@genius3000 For whatever reason I didn't see the bin directory sitting in `run` last time around and thought maybe the template was outdated.

```InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors


InspIRCd-3.7.0```

Here's the cgiirc block:

```<module name="cgiirc">

# Mibbit
    <cgihost type="webirc" password="[snip]" mask="64.62.228.82">
    <cgihost type="webirc" password="[snip]" mask="207.192.75.252">
    <cgihost type="webirc" password="[snip]" mask="78.129.202.38">
    <cgihost type="webirc" password="[snip]" mask="109.169.29.95">

# Lounge
    <cgihost type="webirc" password="[snip]" mask="[IP address]">```

Also, it's funny you mention a host vs. IP based ELINE, when I tried via *@(IP) the ELINE didn't work at all, users were hitting the overlapping GLINE. Removing that one and switching to a host-based GLINE that matched the webirc server then allowed people to connect.

In the immediate term I can't reproduce this as I had AWS set up a reverse DNS record for the webirc client so there will be no issues with the overlapping lines as there's no longer an name-based overlap. But I am going to set up a second Lounge server and not have it be common knowledge so I can continue working through this with you guys probably in a day or two.

**Comment by SadieCat** [comment] 2020-12-01 11:02
This should have been fixed in the latest release.

**Closed by SadieCat** 2020-12-01 11:02 UTC
Labels: bug
