### ISSUE TITLE
[Feature req] Operprefixes based on oper type/class

### ISSUE THREAD

**Issue by Brainscrewer** [inspircd/inspircd#1439] opened 2017-12-14 22:39 UTC
I would like to see the possbility to manage oper-prefixes per oper-class. I.E: 'Senior-operator'-type has a prefix of '!' and 'junior operator'-type does not have a prefix. By default this option would be off, and every operator would get an ! as prefix.

This could also be combined with multiple oper-prefixes (each type a different prefix, which could be configured in the modules.conf)

**Comment by SaberUK** [comment] 2018-03-22 14:03
I've been thinking about this and I think a good way to implement it would be to integrate it with the customprefix module so you define your oper prefixes with `<customprefix>` and then set something like `operprefixes="yo"` in the oper block. What do you think?

**Comment by Brainscrewer** [comment] 2018-03-26 06:59
That sounds like a workable solution, thanks for looking into it! :+1:

**Comment by SaberUK** [comment] 2018-08-24 14:07
Duplicate of #958.

**Closed by SaberUK** 2018-08-24 14:07 UTC
Labels: duplicate, enhancement, minor
