### ISSUE TITLE
m_messageflood appears to not respect exemptchanops

### ISSUE THREAD

**Issue by Techman** [inspircd/inspircd#1742] opened 2020-01-02 07:05 UTC
**Description**

**Steps to reproduce the issue:**

1. Set `+X flood:v` on a channel
2. Have a voiced user trip the flood limit set in the mode (with * to enable kickban)
3. User gets kickbanned despite being voiced

**Describe the results you received:**
User is kickbanned for flooding.

**Describe the results you expected:**
User is not supposed to be kickbanned.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `./bin/inspircd --version`:**
InspIRCd-3.4.0-5637539

**Comment by genius3000** [comment] 2020-01-04 10:47
I've tested this a bit and can confirm the issue. If you have a configured `exemptchanops` setting, the channel mode for the same restriction isn't overriding it. The best I could trace it to was the event priority for OnCheckExemption isn't working as intended (UINT_MAX for core_channel and 100 (default) for m_messageflood) and the handler in core_channel is being ran first. Reloading m_messageflood has **sometimes** allowed it to work (placing it in the list before core_channel).

**Comment by jlu5** [comment] 2020-01-04 18:52
I can confirm this issue on v3.3.0. A while ago I remembering finding how `+X flood:h` stopped working while `+X flood:o` seemed to work OK.

**Comment by SadieCat** [comment] 2020-01-17 10:52
Speculative (untested) fix for this issue: https://github.com/inspircd/inspircd/compare/insp3...SadieCat:insp3+prio

**Comment by genius3000** [comment] 2020-01-17 11:22
I've tested the above fix and can confirm it works.   Tested by having 'flood:o' as a configured exemptchanops value and setting '+X flood:v' on a channel. Voiced and higher are exempted. Removing the +X mode continues to exempt ops and higher as configured.  
I also tested for a possible regression of the issue that was fixed which created this issue - all good there too.

**Closed** 2020-01-17 12:00 UTC
