### ISSUE TITLE
Banned from channel with no bans set in +b list

### ISSUE THREAD

**Issue by killerrabbit** [inspircd/inspircd#1367] opened 2017-09-10 07:59 UTC
**Steps to reproduce the issue:**
Unknown

**Describe the results you received:**
When joining a channel with no bans set in +b(verified with /check output), the channel responds with a "you are banned" reply and redirects you to a redirect channel.

**Describe the results you expected:**
To join the channel.

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happened to one channel. After deleting the channel from inspircd(by having everyone /part) and recreating, the issue disappeared.

**Output of `./bin/inspircd --version`:**
2.0.23

**Comment by SaberUK** [comment] 2017-09-10 08:42
My theory for the cause of this is that the redirect metadata is being stuck on even though the ban has been removed. Probably because either:

1. The ban was removed by services and BeforeMode in the watcher wasn't called.
2. Something is up with removal with regards to the irc::string casemapping.

**Comment by SaberUK** [comment] 2018-03-22 14:25
Is this fixed now #1458 has been merged?

**Comment by SaberUK** [comment] 2018-03-31 12:45
If this is not fixed then please comment and i'll reopen the issue.

**Closed by SaberUK** 2018-03-31 12:45 UTC
Labels: need more information
